arenaWidth = 8 # 场地长
arenaHeight = 6 # 场地高
t1 = 0.1 # 按钮读条时间1
t2 = 0.2 # 按钮读条时间2
t3 = 0.3 # 按钮读条时间3
tRampage = 0.05 # 暴走读条时间
goldBonus = [ 11, 5 ] # 按钮金币奖励，赏金-生存
mode2InitGold = [ 380, 550, 1000, 1200 ] # 生存初始金币， 1-4人
mode2GoldDropRate = [ 3, 5, 8, 10 ] # 生存金币下降速度, 1-4人
maxEnergy = 800.0 # 最大能量值
mode1TotalTime = 300.0 # 赏金模式总时长
mode1CountDown = 10.0 # 赏金模式倒计时长
laserSpeed = 0.17 # 激光亮起间隔(初始速度)
laserSpeedup = [0.014, 0.01, 0.005, 0.004] # 激光每档亮起间隔减少值(加速度)
laserAppearTime = 5.0 # 激光预警时间
laserPauseTime = 9.0 # 激光碰人后硬直时间
energySpeedup = 100.0 # 激光提速每档的能量数
laserSize = 10 # 激光的宽度
uploadTime = 3 # 上传速度
heartbeatTime = 100 # 空闲时上传速度
subUploadTime = 100
subHeartbeatTime = 1000
catchMode = 1 # 0根据位置捕获，1根据接收器捕获
catchLaserNum = 3 # 根据位置捕获时，判断捕获的激光条数

energyBonus = [
[ 0.0, 0.0, 0.0, 0.0 ], # t0-t1能量奖励, 1人
[ 50.0, 37.0, 26.0, 20.0 ], # t1-t2能量奖励, 2人
[ 40.0, 30.0, 22.0, 16.0 ], # t2-t3能量奖励, 3人
[ 30.0, 24.0, 18.0, 12.0 ] # t3能量奖励, 4人
]

initButtonNum = [ 22, 30, 42, 54 ] # 初始按钮个数, 1-4人
buttonHideTime = [ 6.0, 6.0 ] # 按钮触碰后新按钮出现间隔, 赏金-生存
rampageTime = [ 20.0, 20.0 ] # 暴走持续时间, 赏金-生存
firstComboInterval = [ 5.0, 4.0, 3.0, 2.0 ] # 第一次连击时间间隔, 1-4人
comboInterval = [ 3.0, 3.0, 2.0, 2.0 ] # 第n次连击时间间隔, n>1, 1-4人
firstComboExtra = 15.0 # 第一次连击额外能量
comboExtra = 20.0 # 第n次连击额外能量, n>1
playerInvincibleTime = 3.0 # 玩家触碰激光后的无敌时间, 硬件未实现，目前无法配置，固定为3秒
mode1TouchPunish = [100, 50, 30, 20] # 赏金模式触碰激光金币惩罚
mode2TouchPunish = [30, 20, 20, 15] # 生存模式触碰激光金币惩罚
mode2GoldDropInterval = 1.0 # 生存模式每隔几秒金币减少1


# render configures, 显示相关，仅与模拟器有关参数
arenaCellSize = 135 # 格子大小
arenaBorder = 30 # 格子边框大小
playerSize = 48.0 # 玩家大小
webScale = 0.5 # 模拟器显示缩放比例
buttonWidth = 60.0 # 按钮宽度
buttonHeight = 30.0 # 按钮高度
playerSpeed = 200.0 # 玩家移动速度

# 音乐配置
bgIdle = "2"
bgWarmup = ["3", "3"]
bgNormal = ["5", "7"]
bgHigh = ["5", "7"]
bgFull = ["6", "8"]
bgRampage = ["9", "9"]
bgCountdown = ["11", "11"]
bgLeave = ["12", "12"]

# 评级参数配置

goldRank = [
[ 1000, 800, 550, 300],
[ 850, 680, 490, 270],
[ 700, 600, 420, 230],
[ 600, 500, 350, 200 ]
]

goldTeamRank = [
[ 1000, 800, 550, 300],
[ 1700, 1360, 780, 540],
[ 2100, 1800, 1260, 690],
[ 2400, 2000, 1400, 800 ]
]

survivalRank = [
[ 1000, 800, 550, 300],
[ 850, 680, 490, 270],
[ 700, 600, 420, 230],
[ 600, 500, 350, 200 ]
]

survivalTeamRank = [
[ 240000, 180000, 120000, 8000],
[ 240000, 180000, 120000, 8000],
[ 240000, 180000, 120000, 8000],
[ 240000, 180000, 120000, 8000]
]

# 墙壁信息

walls = [
[ 4, 0, 5, 0 ],
[ 1, 0, 1, 1 ],
[ 6, 0, 6, 1 ],
[ 0, 1, 1, 1 ],
[ 2, 1, 3, 1 ],
[ 3, 1, 4, 1 ],
[ 6, 1, 7, 1 ],
[ 2, 1, 2, 2 ],
[ 5, 1, 5, 2 ],
[ 2, 2, 3, 2 ],
[ 3, 2, 4, 2 ],
[ 4, 2, 5, 2 ],
[ 1, 2, 1, 3 ],
[ 6, 2, 6, 3 ],
[ 0, 3, 1, 3 ],
[ 2, 3, 3, 3 ],
[ 4, 3, 5, 3 ],
[ 6, 3, 7, 3 ],
[ 2, 3, 2, 4 ],
[ 3, 3, 3, 4 ],
[ 0, 4, 1, 4 ],
[ 1, 4, 2, 4 ],
[ 4, 4, 5, 4 ],
[ 5, 4, 6, 4 ],
[ 6, 4, 7, 4 ],
[ 4, 4, 4, 5 ],
[ 2, 5, 3, 5 ],
[ 5, 5, 6, 5 ]
]

mainArduino = [
"M-1-1-3-A-5-R",
"M-1-1-4-B-5-R",
"M-1-2-2-A-10-R",
"M-1-3-2-A-5-R",
"M-1-3-4-A-5-L",
"M-1-4-4-B-10-L",
"M-1-5-2-A-5-R",
"M-1-5-4-A-5-L",
"M-1-6-1-A-5-L",
"M-1-6-4-B-5-L",
"M-2-1-3-A-10-R",
"M-2-2-2-A-5-R",
"M-2-2-4-A-5-L",
"M-2-3-1-A-5-L",
"M-2-3-4-B-5-L",
"M-2-4-3-B-10-R",
"M-2-5-1-A-5-L",
"M-2-5-4-B-5-L",
"M-2-6-1-B-5-L",
"M-2-6-3-B-5-R",
"M-3-1-2-A-5-R",
"M-3-1-3-B-5-R",
"M-3-2-1-A-5-L",
"M-3-2-4-B-5-L",
"M-3-3-2-A-5-L",
"M-3-3-3-B-5-R",
"M-3-4-1-A-5-L",
"M-3-4-2-B-5-L",
"M-3-5-2-A-5-R",
"M-3-5-3-B-5-R",
"M-3-6-1-A-10-L",
"M-4-1-3-A-5-R",
"M-4-1-4-B-5-R",
"M-4-2-1-B-10-L",
"M-4-3-3-A-5-L",
"M-4-3-4-B-5-L",
"M-4-4-2-A-5-R",
"M-4-4-4-A-5-L",
"M-4-5-2-B-5-L",
"M-4-5-4-B-5-R",
"M-4-6-1-B-10-L",
"M-5-1-1-B-5-L",
"M-5-1-3-B-5-R",
"M-5-2-2-B-5-R",
"M-5-2-3-A-5-R",
"M-5-3-2-A-10-R",
"M-5-4-2-B-5-R",
"M-5-4-4-B-5-L",
"M-5-5-4-A-10-R",
"M-5-6-1-A-5-L",
"M-5-6-2-B-5-L",
"M-6-1-2-B-5-R",
"M-6-1-3-A-5-R",
"M-6-2-2-A-5-R",
"M-6-2-4-A-5-L",
"M-6-3-4-B-10-L",
"M-6-4-1-B-5-L",
"M-6-4-4-A-5-L",
"M-6-5-3-A-10-R",
"M-6-6-1-B-5-L",
"M-6-6-4-A-5-L",
"M-7-1-3-B-5-R",
"M-7-1-4-A-5-R",
"M-7-2-2-B-5-L",
"M-7-2-4-B-5-R",
"M-7-3-1-B-5-L",
"M-7-3-2-A-5-L",
"M-7-4-3-A-10-R",
"M-7-5-1-B-5-L",
"M-7-5-2-A-5-L",
"M-7-6-3-A-10-R",
"M-8-1-2-B-5-R",
"M-8-1-3-A-5-R",
"M-8-2-2-A-5-R",
"M-8-2-4-A-5-L",
"M-8-3-2-B-5-R",
"M-8-3-4-B-5-L",
"M-8-4-2-A-10-L",
"M-8-5-2-B-5-L",
"M-8-5-4-B-5-L",
"M-8-6-1-B-5-L",
"M-8-6-2-A-5-L"
]

subArduino = [
"S-1-1",
"S-1-4",
"S-2-1",
"S-2-3",
"S-2-4",
"S-2-5",
"S-3-1",
"S-3-5",
"S-4-1",
"S-4-2",
"S-4-3",
"S-4-5",
"S-5-5",
"S-6-2",
"S-6-3",
"S-6-4",
"S-6-5",
"S-7-1",
"S-7-4"
]

musicArduino = [
"B-1"
]

doorArduino = [
"D-1",
"D-2",
"D-3",
"D-4"
]

# 入口坐标
[arenaEntrance]
x = 0
y = 4

# 出口坐标
[arenaExit]
x = 0
y = 4

# 出场激光配置
[[laserConfig]]
time = 2600
large = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
small = [1, 1, 1, 0, 0]

# wearable location Transfer
[[locationTransfers]]
from = 3
to = 3


#Timerift
#Room1
FakeBooks = [ 1, 2, 3, 4, 5]#正确的假书编号
FakeAnimationTime = 3000
CandlesColor = [ 1, 2, 3, 4, 5, 6]#正确的颜色编号
Constellations = ["a", "b", "c"]#正确的星座名字
ElementSymbol = [1, 2, 3, 4, 5, 6]
Room2OpenDoorDelayTime = 10000
Room3OpenDoorDelayTime = 10000
Room4OpenDoorDelayTime = 10000
Room5OpenDoorDelayTime = 10000
